### ISSUE TITLE
Scanning with `severity_threshold` fails with `Invalid array length`

### ISSUE THREAD

**Issue by EnricoMi** [crazy-max/ghaction-container-scan#10]
#### Steps to reproduce this issue

With `severity_threshold` set, the action fails, without that option it succeeds.

#### Expected behaviour

The action should fail saying the docker image is unhealthy:
https://github.com/crazy-max/ghaction-container-scan#severity-threshold

#### Actual behaviour

The action fails with `Invalid array length`:
https://github.com/EnricoMi/publish-unit-test-result-action/runs/5012959037?check_suite_focus=true#step:8:2

Without the `severity_threshold` option, the actions succeeds:
https://github.com/EnricoMi/publish-unit-test-result-action/runs/5012845758?check_suite_focus=true#step:8:2

```yml
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v2
        with:
          load: true
          push: false
          tags: enricomi/publish-unit-test-result-action:latest
          outputs: type=docker

      - name: Scan for vulnerabilities
        id: scan
        uses: crazy-max/ghaction-container-scan@v1
        with:
          image: enricomi/publish-unit-test-result-action:latest
          dockerfile: ./Dockerfile
          severity_threshold: LOW
          annotations: true
      - name: Upload SARIF file
        if: always() && steps.scan.outputs.sarif != ''
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
```
