### ISSUE TITLE
Allow to set trivy timeout

### ISSUE THREAD

**Issue by EnricoMi** [crazy-max/ghaction-container-scan#11]
I would like to increase the trivy timeout to work around:

```
scan error: image scan failed: failed analysis: analyze error: timeout: context deadline exceeded
```

https://github.com/aquasecurity/trivy/issues/802
https://github.com/horovod/horovod/runs/5018091710?check_suite_focus=true#step:9:20

Is there such an option already? I could not find it.

**Comment by crazy-max** [comment]
Sure we can add that option as input.

**Comment by crazy-max** [comment]
Hum actually you can use the `TRIVY_TIMEOUT` env var:

```yaml
      -
        name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v1
        with:
          image: user/app:latest
        env:
          TRIVY_TIMEOUT: "10m0s"
```
