### ISSUE TITLE
Pass more arguments to trivy

### ISSUE THREAD

**Issue by aapjeisbaas** [crazy-max/ghaction-container-scan#43]
Would it be an idea to have an ENV var that will be used to pass along with the trivy command?
I would like to pass:
```txt
--security-checks vuln
--ignore-unfixed
```

What would make it a bit difficult is that some of the params need a specific location in the command

```
trivy --security-checks vuln image --ignore-unfixed --severity HIGH examples/python-fastapi:latest -d
```

Otherwise I would like ta have a "with" param to set **ignore-unfixed** and **security-checks**

**Comment by crazy-max** [comment]
We could have a `args` input. Would look like this:

```yaml
      -
        name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: user/app:latest
          args: |
            --security-checks vuln
            --ignore-unfixed
```
