### ISSUE TITLE
Scan fails when passing repo owner if it contains upper case characters

### ISSUE THREAD

**Issue by TheSpad** [crazy-max/ghaction-container-scan#6]
### Behaviour
If you're using something like `image: ghcr.io/${{ inputs.repo_owner }}/myimage:latest` to call the scan action and your repo owner name (or image name, but weirdly not tag) contains upper case characters the action will fail because the docker repo name must be in lower case. I know this isn't technically an issue with the action, more with the docker client/repo behaviour, but it would be ideal if the action could lowercase any `image` input to avoid the problem occurring. 

#### Steps to reproduce this issue

1. Setup an action using something like
```yaml
      -
        name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v1
        with:
          image: ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:latest
```
Where your repo owner containers upper case characters (in this case `TheSpad`)

2. Run the Action

#### Expected behaviour

Scan should run against the image

#### Actual behaviour

Scan fails with
```
Error: 2021-11-30T09:52:13.115Z	FATAL	scan error: unable to initialize a scanner: unable to initialize a docker scanner: failed to parse the image name: could not parse reference: ghcr.io/TheSpad/get_iplayer:latest
```

### Configuration

* Repository URL (if public): https://github.com/TheSpad/docker-get_iplayer
* Build URL (if public): https://github.com/TheSpad/docker-get_iplayer/runs/4365527296?check_suite_focus=true

```yml
name: Build Image On Release

on:
  workflow_call:
    inputs:
      repo_owner:
        required: true
        type: string
      app_name:
        required: true
        type: string
      dockerhub_user:
        required: true
        type: string
    secrets:
      dockerhub_password:
        required: true

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.4.0
      -  
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3.6.0
        with:
          images: |
            ${{ inputs.repo_owner }}/${{ inputs.app_name }}
            ghcr.io/${{ inputs.repo_owner }}/${{ inputs.app_name }}
          labels: |
            org.opencontainers.image.title=${{ inputs.app_name }}
            org.opencontainers.image.description=${{ inputs.app_name }}
            org.opencontainers.image.vendor=${{ inputs.repo_owner }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      -
        name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ inputs.dockerhub_user }}
          password: ${{ secrets.dockerhub_password }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ inputs.repo_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/bake-action@v1.6.0
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.docker_meta.outputs.bake-file }}
          targets: image-all
          push: true
      -
        name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v1
        with:
          image: ghcr.io/${{ inputs.repo_owner }}/${{ inputs.app_name }}:${{ steps.docker_meta.outputs.tags }}
```

### Logs
[logs_3160.zip](https://github.com/crazy-max/ghaction-container-scan/files/7624852/logs_3160.zip)
