### ISSUE TITLE
Scans only work with amd64 images

### ISSUE THREAD

**Issue by TheSpad** [crazy-max/ghaction-container-scan#9]
#### Steps to reproduce this issue

1. Build an image with only arm64 and/or arm32 manifests
2. Run scan action against it

#### Expected behaviour

Scanning should be possible as trivy provide arm binaries

#### Actual behaviour

> Error: 2021-12-13T23:32:23.703Z	FATAL	scan error: unable to initialize a scanner: unable to initialize a docker scanner: 3 errors occurred:
	* unable to inspect the image (ghcr.io/thespad/dive:v0.10.0-spad003): Error: No such image: ghcr.io/thespad/dive:v0.10.0-spad003
	* unable to initialize Podman client: no podman socket found: stat podman/podman.sock: no such file or directory
	* no child with platform linux/amd64 in index ghcr.io/thespad/dive:v0.10.0-spad003

### Configuration

* Repository URL (if public):  https://github.com/TheSpad/docker-dive
* Build URL (if public):  https://github.com/TheSpad/docker-dive/runs/4513428777?check_suite_focus=true

```yml
      -
        name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v1
        with:
          image: ${{ fromJSON(steps.docker_meta.outputs.json).tags[0] }}
```

### Logs
[logs_72.zip](https://github.com/crazy-max/ghaction-container-scan/files/7734875/logs_72.zip)

**Comment by crazy-max** [comment]
Hum yeah that might be an issue with the container scanner. Can you try with:

```yml
      -
        name: Build and push
        uses: docker/bake-action@v1.6.0
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.docker_meta.outputs.bake-file }}
          targets: image-all
          push: true
      -
        name: OCI
        uses: docker/bake-action@v1.6.0
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.docker_meta.outputs.bake-file }}
          targets: image-all
          set: *.output=type=oci,dest=/tmp/image.tar
      -
        name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v1
        with:
          tarball: /tmp/image.tar
```
